dataset:
  root: /data1/zz/data_wl/dataset_R3N/

  train:  # LMDB
    type: Vimeo90KDataset

    # for lmdb   training_fixed_rate_200
    gt_folder: /data1/zz/data_wl/RUF_data/raw_qp37_train_image/
    lq_folder: /data1/zz/data_wl/RUF_data/train_lqs/bicubic_downsample_x2_compress_qp42_train_pic/
    ref_folder: /data1/zz/data_wl/RUF_data/train_ref_infinity/ref_qp47_infinity/
    
    # for dataset
    gt_path: /data1/zz/data_wl/RUF_data/RUF_lmdb_infinity/E3N_dataset_gt37.lmdb
    lq_path: /data1/zz/data_wl/RUF_data/RUF_lmdb_infinity/bicubic_R3N_dataset_lq42.lmdb
    ref_path: /data1/zz/data_wl/RUF_data/RUF_lmdb_infinity/R3N_dataset_ref47.lmdb
    meta_info_fp: meta_info.txt
    meta_path: /data1/zz/data_wl/RUF_data/raw_qp37_train_image/train_raw_108.txt
    gt_size: 128  # ground truth patch size: gt_size * gt_size
    use_flip: True
    use_rot: True  # rotation per 90 degrees
    random_reverse: False

    # for datasampler
    enlarge_ratio: 10  # enlarge dataset by randomly cropping.

    # for dataloader
    num_worker_per_gpu: 12  # 12 in total. mainly affect IO speed
    batch_size_per_gpu: 8  # bs=32, divided by 2 GPUs

  val: # Disk IO
    type: VideoTestMFQEv2Dataset
    #root: /media/x/Database/MFQEv2/
    gt_path: test_18/raw/
    lq_path: test_18/HM16.5_LDP/QP37/
    #meta_info_fp: meta_info.txt
    #enlarge_ratio: 1
    #use_flip: False
    #use_rot: False
    #random_reverse: False

    test:
      type: VideoTestMFQEv2Dataset
      gt_path: test_18/raw/
      lq_path: test_18/HM16.5_LDP/QP37/

network:
  radius: 2  # total num of input frame = 2 * radius + 1

train:
  exp_name: /data1/zz/data_wl/exp_RUF_infinity/1e-5_300_RUF_qp42_refqp47  # default: timestr. None: ~
  random_seed: 7
  pre-val: False  # evaluate criterion before training, e.g., ori PSNR
  num_iter: !!float 10e+5
  interval_print: !!float 100
  interval_val: !!float 5e+3  # also save model
#  interval_val: !!float 100  # also save model
  pbar_len: 100

  optim:
    type: Adam
    lr: !!float 1e-5  # init lr of scheduler
    betas: [0.9, 0.999]
    eps: !!float 1e-08

  scheduler:
    is_on: False
    type: CosineAnnealingRestartLR
    periods: [!!float 5e+4, !!float 5e+4, !!float 5e+4, !!float 5e+4, !!float 5e+4, !!float 5e+4]  # epoch interval
    restart_weights: [1, 0.5, 0.5, 0.5, 0.5, 0.5]
    eta_min: !!float 1e-7

  loss:
    type: CharbonnierLoss
    eps: !!float 1e-6

  criterion:
    type: PSNR
    unit: dB

test:
  restore_iter: !!float 610000
  pbar_len: 100

  criterion:
    type: PSNR
    unit: dB